name: Slack Pull Request
on:
  pull_request:

jobs:
  slack_pr_opened:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_COLOR: "#f50057"
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: GitHub Actions
          SLACK_ICON: https://raw.githubusercontent.com/github/explore/2c7e603b797535e5ad8b4beb575ab3b7354666e1/topics/actions/actions.png
          SLACK_TITLE: PR Opened üßë‚Äçüíª
